
var VERSION='0.1'
var FULL_VERSION='0.1'
using namespace='System.IO'

use-standard-lifecycle
k-standard-goals

#build-pack target='compile'
   var nugetExe='${E("KOREBUILD_NUGET_EXE") ?? Path.Combine(Directory.GetCurrentDirectory(), ".build/nuget.exe")}'
   dotnet command='msbuild packaging/pack.proj /nologo /t:Pack /p:NuGetExe="${nugetExe}"'