
var VERSION='0.1'
var FULL_VERSION='0.1'

use-standard-lifecycle
k-standard-goals

#build-pack target='compile'
   dotnet command='msbuild packaging/pack.proj /nologo /t:Pack'

#push-packages target="verify"
    @{
        if (IsTeamCity)
        {
            Environment.SetEnvironmentVariable("NUGET_PUBLISH_FEED", "https://dotnet.myget.org/F/aspnetcore-feature-work/api/v2/package");
            CallTarget("nuget-install");
        }
    }
