//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EntityFrameworkCore.Tools.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.EntityFrameworkCore.Tools.DotNet.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Build failed..
        /// </summary>
        public static string BuildFailed {
            get {
                return ResourceManager.GetString("BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to retrieve project metadata. Ensure it&apos;s an MSBuild-based .NET Core project. If you&apos;re using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option..
        /// </summary>
        public static string GetMetadataFailed {
            get {
                return ResourceManager.GetString("GetMetadataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one project was found in the current working directory. Use the --project option..
        /// </summary>
        public static string MultipleProjects {
            get {
                return ResourceManager.GetString("MultipleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one project was found in directory &apos;{0}&apos;. Specify one using its file name..
        /// </summary>
        public static string MultipleProjectsInDirectory {
            get {
                return ResourceManager.GetString("MultipleProjectsInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one startup project was found in directory &apos;{0}&apos;. Specify one using its file name..
        /// </summary>
        public static string MultipleStartupProjects {
            get {
                return ResourceManager.GetString("MultipleStartupProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Startup project &apos;{0}&apos; targets framework &apos;.NETStandard&apos;. This  framework is not intended for execution and may fail to resolve runtime dependencies. If so, specify a different project using the --startup-project option and try again..
        /// </summary>
        public static string NETStandardStartupProject {
            get {
                return ResourceManager.GetString("NETStandardStartupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No project was found. Change the current working directory or use the --project option..
        /// </summary>
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No project was found in directory &apos;{0}&apos;..
        /// </summary>
        public static string NoProjectInDirectory {
            get {
                return ResourceManager.GetString("NoProjectInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No startup project was found in directory &apos;{0}&apos;..
        /// </summary>
        public static string NoStartupProject {
            get {
                return ResourceManager.GetString("NoStartupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Startup project &apos;{0}&apos; targets framework &apos;{1}&apos;. The Entity Framework Core .NET Command Line Tools don&apos;t support this framework..
        /// </summary>
        public static string UnsupportedFramework {
            get {
                return ResourceManager.GetString("UnsupportedFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Writing &apos;{0}&apos;....
        /// </summary>
        public static string WritingFile {
            get {
                return ResourceManager.GetString("WritingFile", resourceCulture);
            }
        }
    }
}
