//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EntityFrameworkCore.Tools.DotNet.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolsDotNetStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ToolsDotNetStrings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.EntityFrameworkCore.Tools.DotNet.Properties.ToolsDotNetStrings", typeof(ToolsDotNetStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Build failed on &apos;{0}&apos;..
        /// </summary>
        public static string BuildFailed {
            get {
                return ResourceManager.GetString("BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Build started....
        /// </summary>
        public static string BuildStarted {
            get {
                return ResourceManager.GetString("BuildStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Build succeeded.
        /// </summary>
        public static string BuildSucceeded {
            get {
                return ResourceManager.GetString("BuildSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not invoke this command on the startup project &apos;{0}&apos;. This version of Entity Framework tools does not support commands on class library projects in ASP.NET Core and .NET Core applications. See http://go.microsoft.com/fwlink/?LinkId=798221 for details and workarounds..
        /// </summary>
        public static string ClassLibrariesNotSupported {
            get {
                return ResourceManager.GetString("ClassLibrariesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not invoke this command on this project. Commands for framework &apos;{0}&apos; are only supported on Windows..
        /// </summary>
        public static string DesktopCommandsRequiresWindows {
            get {
                return ResourceManager.GetString("DesktopCommandsRequiresWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invoking console command in project &apos;{0}&apos;.
        /// </summary>
        public static string LogBeginDispatch {
            get {
                return ResourceManager.GetString("LogBeginDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Setting the data directory to &apos;{0}&apos;..
        /// </summary>
        public static string LogDataDirectory {
            get {
                return ResourceManager.GetString("LogDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Using configuration &apos;{0}&apos;..
        /// </summary>
        public static string LogUsingConfiguration {
            get {
                return ResourceManager.GetString("LogUsingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Using framework &apos;{0}&apos;..
        /// </summary>
        public static string LogUsingFramework {
            get {
                return ResourceManager.GetString("LogUsingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Using startup project &apos;{0}&apos;..
        /// </summary>
        public static string LogUsingStartupProject {
            get {
                return ResourceManager.GetString("LogUsingStartupProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Using target project &apos;{0}&apos;..
        /// </summary>
        public static string LogUsingTargetProject {
            get {
                return ResourceManager.GetString("LogUsingTargetProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not invoke this command because the expected dependency context file [{0}] could not be identified..
        /// </summary>
        public static string MissingDepsJsonFile {
            get {
                return ResourceManager.GetString("MissingDepsJsonFile", resourceCulture);
            }
        }
    }
}
